// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqxslnhcickmlkjlxndo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxeHNsbmhjaWNrbWxramx4bmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4MzQ4MzQsImV4cCI6MjA4MDQxMDgzNH0.MeozisvtPk1cbDa7jVJTCsPdqr1v1yKP9dUmycbAc5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});